### ISSUE TITLE
[Forge/Fabric][1.0.3] incomplete wool stairs variants

### ISSUE THREAD

**Issue by thimblebird** [PTOM76/small-stairs119#4]
at the moment, there are only red and yellow variants of wool stairs

//e: just noticed; they also aren't translated. are they not finished yet or just "experimental"?

**Comment by PTOM76** [comment]
It's definitely not translated.
Thank you for reporting

**Comment by PTOM76** [comment]
It's definitely not translated.
Thank you for reporting

This Small Stairs was ported from 1.2.5, 1.7.10, 1.12.2 to 1.17-1.19, but left as is.
If there's something you want me to add, I'll add it.
