### ISSUE TITLE
Small Stairs not loading anything

### ISSUE THREAD

**Issue by HanatakeYurii** [PTOM76/small-stairs119#6]
Hi!
I'm currently building a modpack with Forge. I already used your mod in 1.19.2 and it was working great.
Now I'm going to 1.20.1 but I encounter a strange issue: the mod is loaded (it appears in the mod list) but no stairs to be found.

I tried again with only these mods:

- Architectury 9.2.4
- Just Enough Items 15.3.0.4
- MCPitanLib 2.2.4-1.20.1-forge
- Small Stairs 1.1.4

All the mods are loaded without complaints but I cannot find any small stairs in the creative search neither in JEI.
There was a similar comment on your CurseForge page, so I might not be the first.

Any idea?
Thanks for your time

EDIT: forgot to say, I use the Forge recommended version 47.2.0, not sure if this has anything to do with this.

**Comment by PTOM76** [comment]
Fixed.
